dist: focal
language: cpp

compiler:
 - clang

before_install:
 - sudo apt update -y
install:
 - sudo apt -y install apache2-dev libcairo2-dev libcurl4-gnutls-dev libiniparser-dev libmapnik-dev

jobs:
  include:
    - stage: tests
      script:
      - ./autogen.sh
      - ./configure
      - make
      - make test
